// filmapp-vue/src/components/filmCard.vue
<template>
    <div class="card film-card">
        <img v-if="movie.img" :src="movie.img" class="card-img-top" alt="Movie Poster" />
        <div class="card-body">
            <h5 class="card-title">{{ movie.title.toUpperCase() }}</h5>
            <p class="card-text"><strong>Director:</strong> {{ movie.director }}</p>
        </div>
        <ul class="list-group list-group-flush">
            <li class="list-group-item"><strong>Year:</strong> {{ movie.year }}</li>
        </ul>
        <div class="card-body d-flex justify-content-between">
            <button class="btn btn-primary">LIKE</button>
            <button class="btn btn-secondary">SHARE</button>
        </div>
    </div>
</template>

<script>
export default {
    props: {
        movie: Object,
    },
};
</script>

<style scoped lang="scss">
.film-card {
    width: 18rem;
    margin-bottom: 40px;
    margin: 10px;
}

.card-img-top {
    margin-top: 10px;
    width: 100%;
    height: 400px;
    object-fit: cover;
    object-position: center;
}

.btn-primary {
    background-color: #232A34;
}
</style>

// FilmApp-Angular/src/app/components/film-card/film-card.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-film-card',
  templateUrl: './film-card.component.html',
  styleUrls: ['./film-card.component.css'],
})

export class FilmCardComponent {

  @Input() movie: any;

  getBackground() {
    return {
      'background-image': `url(${this.movie.img})`,
      'background-size': 'cover',
      'height': '190px',
      'width': '150px',
      'margin-right': '15px',
      'align-self': 'center'
    };
  }

}

<mat-card class="film-card">
  <mat-card-header>
    <mat-card-title>{{ movie.title | uppercase }}</mat-card-title>
    <mat-card-subtitle>{{ movie.year }}</mat-card-subtitle>
  </mat-card-header>
  <img
    mat-card-image
    src="{{ movie.img }}"
    alt="Movie Poster"
    [ngStyle]="getBackground()"
  />
  <mat-card-content>
    <p><strong>Director:</strong> {{ movie.director }}</p>
  </mat-card-content>
  <mat-card-actions>
    <button mat-button mat-raised-button color="primary">LIKE</button>
    <button mat-button mat-raised-button color="secondary">SHARE</button>
  </mat-card-actions>
</mat-card>
